# -*- coding: utf-8 -*-
"""Tutorial1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RW9toGaRwtJ1krtQepqWn8ueHkEJIfiC

DDA - Line Drawing Algorithm
"""

from IPython.core.display import display_latex
import streamlit as st
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

print("Enter the value of x1: ")
x1 = int(input())

print("Enter the value of x2: ")
x2 = int(input())

print("Enter the value of y1")
y1 = int(input())

print("Enter the value of y2")
y2 = int(input())

dx = x2 - x1
dy = y2 - y1

#slope
m = dy/dx

yintercept = y1 - (m*x1)

xcoordinates = y1 + m
ycoordinates = (m * (x1 + 1)) + yintercept


print("X1: ", xcoordinates, ", Y1: ", ycoordinates)

